### ISSUE TITLE
Classification of entries

### ISSUE THREAD

**Issue by spirillen** [asaddon/Asads-Hosts#1]
Hi @asaddon 

I would like to hear if you are able to classify the individual entries in your hosts file. The reason is I haven't noticed any playstation domains before but I would like to have the records classified on www.mypdns.org so they can get the right classifications and if BadWare <https://www.mypdns.org/w/malware/> blocked by my [RPZ](https://www.mypdns.org/w/rpz/) zones

**Comment by asaddon** [comment]
My list is an extremely personal list for my use only ( though anyone is free to use it if they wish ) The domains you see here are all wildcards and I use them with a wildcard ad blocker, the reason I do that is I realize I can shrink by 5K ad blocker hosts list to less than 600 entries if I use the domains as a wildcard and that was the reason this list was created.

Regarding the playstation entries you see, they're again for my personal use case and they are there to block Sony firmware updates for my PS4, they're not any advertisement or tracking URL's so one should not use it.

**Comment by spirillen** [comment]
Cool, so you have been upgrading to the RPZ or similar :100: 

In the future if you find anything useful, please feel veeeeeeeeeeery free to add them to mypdns.org as issues :smirk:
